development:
 adapter: postgresql
 encoding: utf8
 database: da1sbk84c3urgo
 username: wrpntxtkbuiygn
 password:  7PHchDPS5u6_JO1rPjOGMZl77v
 host: localhost
 port: 5432

production:
 adapter: postgresql
 encoding: utf8
 database: da1sbk84c3urgo
 username: wrpntxtkbuiygn
 password:  7PHchDPS5u6_JO1rPjOGMZl77v
 host: 10.7.1.230
 port: 5432

staging:
 adapter: postgresql
 encoding: utf8
 database: da1sbk84c3urgo
 username: wrpntxtkbuiygn
 password:  7PHchDPS5u6_JO1rPjOGMZl77v
 host: 10.7.1.230
 port: 5432